iGym/Gym/urls.py
from django.conf.urls import url
from . import views

app_name = 'Gym'
urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^Trainee/add/$', views.TraineeCreate.as_view(), name='trainee-add'),
    url(r'^Trainee/(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='trainee-detail'),
    url(r'^Trainee/(?P<pk>[0-9]+)/edit/$', views.TraineeUpdate.as_view(), name='trainee-update'),
    url(r'^Trainee/(?P<pk>[0-9]+)/delete/$', views.TraineeDelete.as_view(), name='trainee-delete'),
]

iGym/accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
     url(r'^/$', views.index, name='index'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^login/$', auth_views.login,
        {'template_name': 'accounts/login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout,
        {'next_page': 'accounts:login'}, name='logout'),
    url(r'^password/$', views.change_password, name='change_password'),
]

iGym/iGym/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('Gym.urls')),
    url(r'^Gym/', include('Gym.urls')),
     url(r'^Account/', include('accounts.urls')),
    url(r'^admin/', admin.site.urls),
]

iGym/Gym/models.py
from django.db import models
from django.urls import reverse

# Create your models here.


class Trainee(models.Model):
    name = models.CharField(max_length=100, default="")
    address = models.CharField(max_length=400, default="")
    city = models.CharField(max_length=400, default="")
    state = models.CharField(max_length=400, default="")
    zip_code = models.CharField(max_length=400, default="")

    def __str__(self):
        return self.name + "-" + self.city

    def get_absolute_url(self):
        return reverse('Gym:trainee-detail', kwargs={'pk': self.pk})

iGym/accounts/models.py
from django.db import models

# Create your models here.

iGym/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )

    # def __init__(self, *args, **kwargs):
    #     form = super(SignUpForm, self).__init__(*args, **kwargs)
    #     for visible in form.visible_fields():
    #         visible.field.widget.attrs['class'] = 'form-control'

iGym/Gym/views.py
from django.shortcuts import render
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy

from .models import Trainee



@login_required(login_url='/Account/login/')
def index(request):
    return render(request, 'Gym/index.html', {'message': "Welcome back"})


class TraineeCreate(CreateView):
    model = Trainee
    fields = ['name', 'address', 'city', 'state', 'zip_code']


class TraineeUpdate(UpdateView):
    model = Trainee
    fields = ['name', 'address', 'city', 'state', 'zip_code']


class DetailView(generic.DetailView):
    model = Trainee
    template_name = 'Gym/detail.html'


class TraineeDelete(DeleteView):
    model = Trainee
    success_url = reverse_lazy('Gym:index')

iGym/accounts/views.py
from django.contrib import messages
from django.contrib.auth import login, authenticate, update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.shortcuts import render, redirect
from accounts.forms import SignUpForm

# Create your views here.
def index(request):
    return render(request,'accounts/index.html')

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('Gym:index')
    else:
        form = SignUpForm()
    return render(request, 'accounts/signup.html', {'form': form})


def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(
                request, 'Your password was successfully updated!')
            return redirect('accounts:change_password')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'accounts/change_password.html', {
        'form': form
    })

iGym/Gym/templates/Gym/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title> {% block title %} iGym {% endblock %}
    </title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/flatly/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Kaushan+Script" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'Gym/css/style.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>

<body>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"
                    aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand logo-text" href="{% url 'Gym:index' %}">iGym</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    {% if user.is_authenticated %}
                <ul class="nav navbar-nav">
                    <li class="active">
                        <a href="#">Link
                            <span class="sr-only">(current)</span>
                        </a>
                    </li>
                    <li>
                        <a href="#">Link</a>
                    </li>

                </ul>
                {% endif %}
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="#">
                            {% if user.is_authenticated %} Welcome
                            <span class="text-capitalize"> {{ user.username }}!</span>
                            {% endif %}
                        </a>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            
                            {% if user.is_authenticated %}
                            <li>
                                    <a href="{% url 'accounts:index' %}">Manage</a>
                                </li>
                                <li>
                                    <a href="#">Another action</a>
                                </li>
                                <li role="separator" class="divider"></li>
                            <li>
                                <a href="{% url 'accounts:logout' %}">Logout</a>
                            </li>
                            {% else %}
                                <li>
                                    <a href="{% url 'accounts:signup' %}">Signup</a>
                                </li>
                                <li>
                                    <a href="{% url 'accounts:login' %}">Login</a>
                                </li>
                            {% endif %}

                        </ul>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>
    {% block body %} {% endblock %}
</body>

</html>

iGym/Gym/templates/Gym/detail.html
{{trainee}}

iGym/Gym/templates/Gym/form-template.html
{% load widget_tweaks %}
{% for field in form %}
<div class="form-group">
   
    <label class="control-label col-sm-2">{{ field.label_tag}}</label>
    <div class="col-sm-10">
        {{ field|add_class:"form-control" }}
    </div>
    <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger">
                {{ field.errors }}
            </span>
        </div>
</div>
{% endfor %}

iGym/Gym/templates/Gym/index.html
{% extends 'Gym/base.html' %}

{% block title %} 
iGym
{% endblock %}

{% block body %}
<div class="body-content">
        <h1>{{ message }} to home page</h1>
</div>

{% endblock %}

iGym/Gym/templates/Gym/trainee_form.html
{% extends 'Gym/base.html' %} 
{% block title %}New Trainee {% endblock %} 
{% block body %}

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-6 col-md-offset-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Add New Trainee</h3>
                    <hr>
                        {% if error_message %}
                        <p>
                            <strong>{{ error_message }}</strong>
                        </p>
                        {% endif %}
                    <form class="form-horizontal" method="POST" action="" enctype="multipart/form-data">
                        {% csrf_token %} {% include 'Gym/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

iGym/accounts/templates/accounts/change_password.html
{% extends 'Gym/base.html' %} 
{% load widget_tweaks %}
{% block title %}Login{% endblock %} 
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6 col-xs-12">
            <h2>Change Password</h2>
            <form method="post">
                {% csrf_token %}        
                {% for field in form %}
                <p>
                  {{ field.label_tag }}<br>
                  {{ field|add_class:"form-control" }}
                  {% if field.help_text %}
                    <small style="color: grey">{{ field.help_text| safe }}</small>
                  {% endif %}
                  {% for error in field.errors %}
                    <p style="color: red">{{ error }}</p>
                  {% endfor %}
                </p>
              {% endfor %}
                <button class="btn btn-primary" type="submit">Save changes</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

iGym/accounts/templates/accounts/index.html
{% extends 'Gym/base.html' %} 
{% block title %}Login{% endblock %} 
{% block body %}
<div class="container">
        <div class="row">
            <div class="col-md-6">
                <h2>Manage</h2>
                <a href="{% url 'accounts:change_password' %}">Change Password</a>
            </div>
        </div>
    </div>
{% endblock %}

iGym/accounts/templates/accounts/login.html
{% extends 'Gym/base.html' %}
{% load widget_tweaks %}
{% block title %}Login{% endblock %}

{% block body %}
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1 class="logo-text">iGym</h1>
        <h2>Login</h2>
        <form method="post">
          {% csrf_token %}
          <!-- {{ form.as_p }} -->
          {% for field in form %}
          <p>
            {{ field.label_tag }}<br>
            {{ field|add_class:"form-control" }}
            {% if field.help_text %}
              <small style="color: grey">{{ field.help_text }}</small>
            {% endif %}
            {% for error in field.errors %}
              <p style="color: red">{{ error }}</p>
            {% endfor %}
          </p>
        {% endfor %}
          <button type="submit" class="btn btn-primary">Login</button>
        </form>
        <div style="margin-top:10px;">
            Don't have account? <a href="{% url 'accounts:signup' %}"> Signup here</a>
        </div>
    </div>
  </div>
</div> 
{% endblock %}

iGym/accounts/templates/accounts/signup.html
{% extends 'Gym/base.html' %}
{% load widget_tweaks %}
{% block body %}
<div class="container">
  <div class="col-md-6 col-md-offset-3">
      <h1 class="logo-text">iGym</h1>
      <h2>Sign up</h2>
      <form method="post">
        {% csrf_token %}
        {% for field in form %}
          <p>
            {{ field.label_tag }}<br>
            {{ field|add_class:"form-control" }}
            <!-- {% if field.help_text %}
              <small style="color: grey">{{ field.help_text }}</small>
            {% endif %} -->

            {% for error in field.errors %}
              <p style="color: red">{{ error }}</p>
            {% endfor %}
          </p>
        {% endfor %}
        <button class="btn btn-primary btn-block" type="submit">Sign up</button>
      </form>
    <div style="margin-top:10px;">
        Already have account? <a href="{% url 'accounts:login' %}"> Login here</a>
    </div>

  </div>
</div>

{% endblock %}